### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by juliandm101** [Mecatrogrupo/custom-nfc-tags#1]
Hola gente, antes que nada muchas gracias por compartir el proyecto, ya comprè las cosas para hacerlo.
Como sugerencia, estarìa bueno poner en el paso a paso, que antes de cortar la tarjeta original, uno deberia anotar el numero de la misma (o sacarle una foto), antes de tirar todos los pedazos.
Un abrazo!

**Comment by Mecatrogrupo** [comment]
Muchísimas gracias por la compra y la recomendación, justo estábamos
actualizando las instrucciones escritas así que nos vino bárbaro. Estamos
tan acostumbrados a leer el llavero con el celu cuando lo terminamos que
nos olvidamos que no todos tienen NFC...
Si te interesa el tema fijate en los próximos días que estamos pensando en
hacer un kit con capacitor variable e instrucciones para convertir
cualquier cosa RFID.
